turn view to a function when layout exists
bungle/lua-resty-template pull request #43
Opened 2020-09-25 13:46 UTC by xiangnanscu

2020-09-29 21:53 UTC, bungle commented on lib/resty/template.lua
> +                    context.view = function() return template.process(view, context) end
Should we make it possible to override the `context`: `{* view { foo = "bar" } *}`?
```suggestion
                    context.view = function(ctx) return template.process(view, ctx, context) end
```

2020-09-30 07:10 UTC, xiangnanscu commented
hello. Should the other three places need to apply this change?

2020-10-05 22:42 UTC, bungle commented
> hello. Should the other three places need to apply this change?

Yes, all three.

2020-10-06 12:47 UTC, xiangnanscu commented
@bungle done

2020-10-07 15:44 UTC, bungle requested changes

2020-10-07 15:44 UTC, bungle commented on lib/resty/template.lua
> +                    context.view = function() return template.process(view, context) end
Is it still missing here?

2020-10-08 00:44 UTC, xiangnanscu commented
@bungle sorry. done

2020-10-11 09:28 UTC, merged